export interface YouTubeChannel {
  id: string;
  title: string;
  description: string;
  thumbnailUrl?: string | undefined;
  videoCount: number;
}

export interface YouTubeVideo {
  id: string;
  title: string;
  description: string;
  publishedAt: string;
  duration: string; // ISO 8601 duration format
  thumbnailUrl?: string | undefined;
  channelId: string;
}

export interface YouTubeApiError {
  code: number;
  message: string;
  errors?: Array<{
    domain: string;
    reason: string;
    message: string;
  }>;
}

export interface RateLimitConfig {
  maxRetries: number;
  baseDelay: number;
  maxDelay: number;
}

export interface YouTubeApiResponse<T> {
  success: boolean;
  data?: T;
  error?: YouTubeApiError;
  retryAfter?: number;
}

export interface SubtitleSegment {
  text: string;
  start: number; // in seconds
  duration: number; // in seconds
}

export interface TranscriptResponse {
  videoId: string;
  language: string;
  segments: SubtitleSegment[];
  isAutoGenerated: boolean;
}

export interface TranscriptApiResponse<T> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
  };
}