import { YoutubeTranscript } from 'youtube-transcript';
import { 
  SubtitleSegment, 
  TranscriptResponse, 
  TranscriptApiResponse,
  RateLimitConfig 
} from '../types/youtube';

export class YouTubeTranscriptService {
  private rateLimitConfig: RateLimitConfig;
  private lastRequestTime: number = 0;

  constructor(rateLimitConfig?: Partial<RateLimitConfig>) {
    this.rateLimitConfig = {
      maxRetries: 3,
      baseDelay: 1000,
      maxDelay: 30000,
      ...rateLimitConfig
    };
  }

  /**
   * Extracts subtitles from a YouTube video
   */
  async extractSubtitles(videoId: string, language?: string): Promise<TranscriptApiResponse<TranscriptResponse>> {
    return this.executeWithRetry(async () => {
      // Apply rate limiting
      await this.applyRateLimit();

      const transcriptData = await YoutubeTranscript.fetchTranscript(videoId, {
        lang: language || 'en'
      });

      if (!transcriptData || transcriptData.length === 0) {
        return {
          success: false,
          error: {
            code: 'NO_TRANSCRIPT',
            message: 'No transcript available for this video'
          }
        };
      }

      // Process and format transcript data
      const segments: SubtitleSegment[] = transcriptData.map(item => ({
        text: this.cleanTranscriptText(item.text),
        start: item.offset / 1000, // Convert milliseconds to seconds
        duration: item.duration / 1000 // Convert milliseconds to seconds
      }));

      return {
        success: true,
        data: {
          videoId,
          language: language || 'en',
          segments,
          isAutoGenerated: true // youtube-transcript typically gets auto-generated transcripts
        }
      };
    });
  }

  /**
   * Extracts subtitles with multiple language fallbacks
   */
  async extractSubtitlesWithFallback(
    videoId: string, 
    preferredLanguages: string[] = ['en', 'en-US', 'en-GB']
  ): Promise<TranscriptApiResponse<TranscriptResponse>> {
    let lastError: any;

    for (const language of preferredLanguages) {
      const result = await this.extractSubtitles(videoId, language);
      
      if (result.success) {
        return result;
      }

      lastError = result.error;

      // If the error is not language-related, don't try other languages
      if (result.error?.code !== 'LANGUAGE_NOT_AVAILABLE' && 
          result.error?.code !== 'NO_TRANSCRIPT') {
        break;
      }
    }

    return {
      success: false,
      error: lastError || {
        code: 'NO_TRANSCRIPT',
        message: 'No transcript available in any of the requested languages'
      }
    };
  }

  /**
   * Processes transcript text to extract meaningful content with timestamps
   */
  async processTranscriptForSearch(videoId: string): Promise<TranscriptApiResponse<{
    videoId: string;
    fullText: string;
    timestampedSegments: Array<{
      text: string;
      startTime: number;
      endTime: number;
    }>;
  }>> {
    const transcriptResult = await this.extractSubtitlesWithFallback(videoId);

    if (!transcriptResult.success || !transcriptResult.data) {
      return {
        success: false,
        error: transcriptResult.error || {
          code: 'NO_TRANSCRIPT',
          message: 'Failed to extract transcript'
        }
      };
    }

    const segments = transcriptResult.data.segments;
    const fullText = segments.map(segment => segment.text).join(' ');

    // Group segments into meaningful chunks (sentences or phrases)
    const timestampedSegments = this.groupSegmentsIntoChunks(segments);

    return {
      success: true,
      data: {
        videoId,
        fullText,
        timestampedSegments
      }
    };
  }

  /**
   * Groups subtitle segments into meaningful chunks for better search results
   */
  private groupSegmentsIntoChunks(segments: SubtitleSegment[]): Array<{
    text: string;
    startTime: number;
    endTime: number;
  }> {
    const chunks: Array<{
      text: string;
      startTime: number;
      endTime: number;
    }> = [];

    let currentChunk = '';
    let chunkStartTime = 0;
    let chunkEndTime = 0;

    for (let i = 0; i < segments.length; i++) {
      const segment = segments[i];
      
      if (!segment) continue;
      
      if (currentChunk === '') {
        // Start new chunk
        currentChunk = segment.text;
        chunkStartTime = segment.start;
        chunkEndTime = segment.start + segment.duration;
      } else {
        // Add to current chunk
        currentChunk += ' ' + segment.text;
        chunkEndTime = segment.start + segment.duration;
      }

      // End chunk on sentence boundaries or after 30 seconds
      const shouldEndChunk = 
        segment.text.match(/[.!?]$/) || // Sentence ending
        (chunkEndTime - chunkStartTime) > 30 || // Max 30 seconds per chunk
        i === segments.length - 1; // Last segment

      if (shouldEndChunk) {
        chunks.push({
          text: currentChunk.trim(),
          startTime: chunkStartTime,
          endTime: chunkEndTime
        });

        currentChunk = '';
      }
    }

    return chunks;
  }

  /**
   * Executes a function with retry logic for transcript extraction
   */
  private async executeWithRetry<T>(
    operation: () => Promise<TranscriptApiResponse<T>>
  ): Promise<TranscriptApiResponse<T>> {
    let lastError: any;

    for (let attempt = 0; attempt <= this.rateLimitConfig.maxRetries; attempt++) {
      try {
        const result = await operation();
        
        // If successful or non-retryable error, return immediately
        if (result.success || !this.isRetryableTranscriptError(result.error)) {
          return result;
        }

        lastError = result.error;

        // Don't retry on the last attempt
        if (attempt === this.rateLimitConfig.maxRetries) {
          break;
        }

        // Calculate delay with exponential backoff
        const delay = Math.min(
          this.rateLimitConfig.baseDelay * Math.pow(2, attempt),
          this.rateLimitConfig.maxDelay
        );

        // Add jitter to prevent thundering herd
        const jitteredDelay = delay + Math.random() * 1000;

        await this.sleep(jitteredDelay);

      } catch (error: any) {
        lastError = this.parseTranscriptError(error);

        // Check if error is retryable
        if (!this.isRetryableTranscriptError(lastError)) {
          break;
        }

        // Don't retry on the last attempt
        if (attempt === this.rateLimitConfig.maxRetries) {
          break;
        }

        const delay = Math.min(
          this.rateLimitConfig.baseDelay * Math.pow(2, attempt),
          this.rateLimitConfig.maxDelay
        );
        await this.sleep(delay);
      }
    }

    return {
      success: false,
      error: lastError || {
        code: 'UNKNOWN_ERROR',
        message: 'Unknown error occurred during transcript extraction'
      }
    };
  }

  /**
   * Applies rate limiting to prevent overwhelming the transcript service
   */
  private async applyRateLimit(): Promise<void> {
    const now = Date.now();
    const timeSinceLastRequest = now - this.lastRequestTime;
    
    // Ensure minimum delay between requests (500ms for transcript API)
    if (timeSinceLastRequest < 500) {
      await this.sleep(500 - timeSinceLastRequest);
    }

    this.lastRequestTime = Date.now();
  }

  /**
   * Determines if a transcript error is retryable
   */
  private isRetryableTranscriptError(error?: { code: string; message: string }): boolean {
    if (!error) return false;

    // Retry on network errors, rate limits, and temporary failures
    return error.code === 'NETWORK_ERROR' ||
           error.code === 'RATE_LIMITED' ||
           error.code === 'TEMPORARY_FAILURE' ||
           error.code === 'TIMEOUT';
  }

  /**
   * Parses error from transcript extraction
   */
  private parseTranscriptError(error: any): { code: string; message: string } {
    const errorMessage = typeof error === 'string' ? error : error?.message || '';
    
    if (errorMessage.includes('Could not retrieve a transcript')) {
      return {
        code: 'NO_TRANSCRIPT',
        message: 'No transcript available for this video'
      };
    }
    if (errorMessage.toLowerCase().includes('language')) {
      return {
        code: 'LANGUAGE_NOT_AVAILABLE',
        message: 'Transcript not available in requested language'
      };
    }
    if (errorMessage.toLowerCase().includes('disabled')) {
      return {
        code: 'TRANSCRIPT_DISABLED',
        message: 'Transcripts are disabled for this video'
      };
    }
    if (errorMessage.toLowerCase().includes('network') || errorMessage.toLowerCase().includes('timeout')) {
      return {
        code: 'NETWORK_ERROR',
        message: 'Network error while fetching transcript'
      };
    }
    if (errorMessage.toLowerCase().includes('rate') || errorMessage.toLowerCase().includes('limit')) {
      return {
        code: 'RATE_LIMITED',
        message: 'Rate limited by transcript service'
      };
    }

    return {
      code: 'UNKNOWN_ERROR',
      message: errorMessage || 'Unknown error occurred during transcript extraction'
    };
  }

  /**
   * Cleans transcript text by removing HTML entities and extra whitespace
   */
  private cleanTranscriptText(text: string): string {
    return text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/\s+/g, ' ')
      .trim();
  }

  /**
   * Sleep utility function
   */
  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}