import { YouTubeTranscriptService } from '../YouTubeTranscriptService';
import { YoutubeTranscript } from 'youtube-transcript';

// Mock the youtube-transcript module
jest.mock('youtube-transcript');
const mockYoutubeTranscript = YoutubeTranscript as jest.Mocked<typeof YoutubeTranscript>;

describe('YouTubeTranscriptService', () => {
  let service: YouTubeTranscriptService;

  beforeEach(() => {
    jest.clearAllMocks();
    service = new YouTubeTranscriptService();
  });

  describe('extractSubtitles', () => {
    it('should successfully extract subtitles from a video', async () => {
      const mockTranscriptData = [
        {
          text: 'Hello world',
          offset: 0,
          duration: 2000
        },
        {
          text: 'This is a test',
          offset: 2000,
          duration: 3000
        }
      ];

      mockYoutubeTranscript.fetchTranscript.mockResolvedValue(mockTranscriptData);

      const result = await service.extractSubtitles('test-video-id');

      expect(result.success).toBe(true);
      expect(result.data).toEqual({
        videoId: 'test-video-id',
        language: 'en',
        segments: [
          {
            text: 'Hello world',
            start: 0,
            duration: 2
          },
          {
            text: 'This is a test',
            start: 2,
            duration: 3
          }
        ],
        isAutoGenerated: true
      });

      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledWith('test-video-id', {
        lang: 'en'
      });
    });

    it('should handle videos with no transcript available', async () => {
      mockYoutubeTranscript.fetchTranscript.mockResolvedValue([]);

      const result = await service.extractSubtitles('no-transcript-video');

      expect(result.success).toBe(false);
      expect(result.error).toEqual({
        code: 'NO_TRANSCRIPT',
        message: 'No transcript available for this video'
      });
    });

    it('should handle transcript extraction errors', async () => {
      mockYoutubeTranscript.fetchTranscript.mockRejectedValue(
        new Error('Could not retrieve a transcript for the video')
      );

      const result = await service.extractSubtitles('error-video');

      expect(result.success).toBe(false);
      expect(result.error?.code).toBe('NO_TRANSCRIPT');
    });

    it('should clean HTML entities in transcript text', async () => {
      const mockTranscriptData = [
        {
          text: 'Hello &amp; welcome to &quot;our show&quot;',
          offset: 0,
          duration: 3000
        }
      ];

      mockYoutubeTranscript.fetchTranscript.mockResolvedValue(mockTranscriptData);

      const result = await service.extractSubtitles('test-video-id');

      expect(result.success).toBe(true);
      expect(result.data?.segments[0]?.text).toBe('Hello & welcome to "our show"');
    });

    it('should use specified language', async () => {
      const mockTranscriptData = [
        {
          text: 'Hola mundo',
          offset: 0,
          duration: 2000
        }
      ];

      mockYoutubeTranscript.fetchTranscript.mockResolvedValue(mockTranscriptData);

      const result = await service.extractSubtitles('test-video-id', 'es');

      expect(result.success).toBe(true);
      expect(result.data?.language).toBe('es');
      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledWith('test-video-id', {
        lang: 'es'
      });
    });
  });

  describe('extractSubtitlesWithFallback', () => {
    it('should try multiple languages and return first successful result', async () => {
      const mockTranscriptData = [
        {
          text: 'Hello world',
          offset: 0,
          duration: 2000
        }
      ];

      mockYoutubeTranscript.fetchTranscript
        .mockRejectedValueOnce(new Error('Language not available'))
        .mockResolvedValueOnce(mockTranscriptData);

      const result = await service.extractSubtitlesWithFallback('test-video-id', ['es', 'en']);

      expect(result.success).toBe(true);
      expect(result.data?.language).toBe('en');
      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledTimes(2);
    });

    it('should return error if no languages work', async () => {
      mockYoutubeTranscript.fetchTranscript.mockRejectedValue(
        new Error('Could not retrieve a transcript for the video')
      );

      const result = await service.extractSubtitlesWithFallback('no-transcript-video');

      expect(result.success).toBe(false);
      expect(result.error?.code).toBe('NO_TRANSCRIPT');
    });

    it('should stop trying languages on non-language-related errors', async () => {
      mockYoutubeTranscript.fetchTranscript.mockRejectedValue(
        new Error('Network error')
      );

      const result = await service.extractSubtitlesWithFallback('error-video', ['en', 'es', 'fr']);

      expect(result.success).toBe(false);
      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledTimes(1);
    });
  });

  describe('processTranscriptForSearch', () => {
    it('should process transcript into searchable format', async () => {
      const mockTranscriptData = [
        {
          text: 'Hello everyone.',
          offset: 0,
          duration: 2000
        },
        {
          text: 'Welcome to our show.',
          offset: 2000,
          duration: 3000
        },
        {
          text: 'Today we will discuss',
          offset: 5000,
          duration: 2500
        },
        {
          text: 'artificial intelligence.',
          offset: 7500,
          duration: 2500
        }
      ];

      mockYoutubeTranscript.fetchTranscript.mockResolvedValue(mockTranscriptData);

      const result = await service.processTranscriptForSearch('test-video-id');

      expect(result.success).toBe(true);
      expect(result.data?.fullText).toBe(
        'Hello everyone. Welcome to our show. Today we will discuss artificial intelligence.'
      );
      expect(result.data?.timestampedSegments).toHaveLength(2);
      expect(result.data?.timestampedSegments[0]).toEqual({
        text: 'Hello everyone. Welcome to our show.',
        startTime: 0,
        endTime: 5
      });
    });

    it('should handle transcript extraction failure', async () => {
      mockYoutubeTranscript.fetchTranscript.mockRejectedValue(
        new Error('Could not retrieve a transcript for the video')
      );

      const result = await service.processTranscriptForSearch('no-transcript-video');

      expect(result.success).toBe(false);
      expect(result.error?.code).toBe('NO_TRANSCRIPT');
    });
  });

  describe('retry logic', () => {
    it('should retry on retryable errors', async () => {
      mockYoutubeTranscript.fetchTranscript
        .mockRejectedValueOnce(new Error('Network error'))
        .mockResolvedValueOnce([
          {
            text: 'Hello world',
            offset: 0,
            duration: 2000
          }
        ]);

      const result = await service.extractSubtitles('test-video-id');

      expect(result.success).toBe(true);
      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledTimes(2);
    });

    it('should not retry on non-retryable errors', async () => {
      mockYoutubeTranscript.fetchTranscript.mockRejectedValue(
        new Error('Could not retrieve a transcript for the video')
      );

      const result = await service.extractSubtitles('no-transcript-video');

      expect(result.success).toBe(false);
      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledTimes(1);
    });

    it('should fail after max retries', async () => {
      mockYoutubeTranscript.fetchTranscript.mockRejectedValue(
        new Error('Network timeout')
      );

      const result = await service.extractSubtitles('timeout-video');

      expect(result.success).toBe(false);
      expect(mockYoutubeTranscript.fetchTranscript).toHaveBeenCalledTimes(4); // Initial + 3 retries
    }, 10000);
  });

  describe('rate limiting', () => {
    it('should apply rate limiting between requests', async () => {
      const mockTranscriptData = [
        {
          text: 'Test',
          offset: 0,
          duration: 1000
        }
      ];

      mockYoutubeTranscript.fetchTranscript.mockResolvedValue(mockTranscriptData);

      const startTime = Date.now();
      
      // Make sequential requests to test rate limiting
      await service.extractSubtitles('video1');
      await service.extractSubtitles('video2');

      const endTime = Date.now();
      const duration = endTime - startTime;

      // Should take at least 500ms due to rate limiting
      expect(duration).toBeGreaterThan(400);
    });
  });

  describe('error parsing', () => {
    it('should parse different types of transcript errors correctly', async () => {
      const testCases = [
        {
          error: 'Could not retrieve a transcript for the video',
          expectedCode: 'NO_TRANSCRIPT'
        },
        {
          error: 'language not available',
          expectedCode: 'LANGUAGE_NOT_AVAILABLE'
        },
        {
          error: 'transcripts are disabled',
          expectedCode: 'TRANSCRIPT_DISABLED'
        },
        {
          error: new Error('Network timeout'),
          expectedCode: 'NETWORK_ERROR'
        }
      ];

      for (const testCase of testCases) {
        mockYoutubeTranscript.fetchTranscript.mockRejectedValueOnce(testCase.error);
        
        const result = await service.extractSubtitles('test-video');
        
        expect(result.success).toBe(false);
        expect(result.error?.code).toBe(testCase.expectedCode);
      }
    });
  });

  describe('segment grouping', () => {
    it('should group segments into meaningful chunks', async () => {
      const mockTranscriptData = [
        { text: 'First sentence.', offset: 0, duration: 2000 },
        { text: 'Second sentence.', offset: 2000, duration: 2000 },
        { text: 'Third part', offset: 4000, duration: 2000 },
        { text: 'of same thought.', offset: 6000, duration: 2000 },
        { text: 'Final sentence.', offset: 8000, duration: 2000 }
      ];

      mockYoutubeTranscript.fetchTranscript.mockResolvedValue(mockTranscriptData);

      const result = await service.processTranscriptForSearch('test-video-id');

      expect(result.success).toBe(true);
      expect(result.data?.timestampedSegments).toHaveLength(3);
      
      // First chunk should end at sentence boundary
      expect(result.data?.timestampedSegments?.[0]?.text).toBe('First sentence.');
      
      // Second chunk should end at sentence boundary
      expect(result.data?.timestampedSegments?.[1]?.text).toBe('Second sentence.');
      
      // Third chunk should contain remaining segments
      expect(result.data?.timestampedSegments?.[2]?.text).toBe('Third part of same thought. Final sentence.');
    });
  });
});